# Generated by Django 2.1.3 on 2018-11-24 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppl_registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
