# Generated by Django 2.1.3 on 2018-11-24 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppl_registration', '0002_auto_20181124_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='spots_available',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='waitlist_spots_available',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
