# Generated by Django 2.1.3 on 2018-11-25 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppl_registration', '0003_auto_20181124_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='initial_spots',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='initial_waitlist',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='spots_available',
            field=models.PositiveIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='event',
            name='waitlist_spots_available',
            field=models.PositiveIntegerField(default=None),
        ),
    ]
