# Generated by Django 2.1.3 on 2018-11-26 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppl_registration', '0005_auto_20181125_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='initial_spots',
        ),
        migrations.RemoveField(
            model_name='event',
            name='initial_waitlist',
        ),
        migrations.AlterField(
            model_name='event',
            name='spots_available',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='waitlist_spots_available',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
