# Generated by Django 2.1.3 on 2018-11-26 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppl_registration', '0006_auto_20181125_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='wait_list',
            field=models.BooleanField(default=0),
        ),
    ]
