# Generated by Django 2.1.3 on 2018-12-03 05:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppl_registration', '0007_registration_wait_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='registration_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
