# Generated by Django 2.1.3 on 2018-12-03 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppl_registration', '0008_registration_registration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
